### ISSUE TITLE
can not close the overlay after resolve the check errors

### ISSUE THREAD

**Issue by yuanlin1995** [time4dev/vite-esbuild-typescript-checker#4]
in my program,  can not close the overlay after resolve the check errors
but in your example, it work;  emmm... I don't know why;

in your code: 
src/helper.ts  -> handleMessage - line138
when the issuse is [], should you send a message to tell the ws  that there is no error now?

**Comment by time4dev** [comment]
it work fin
![BN4EnQ7mem](https://user-images.githubusercontent.com/54905262/144576885-ad74b053-684b-4e31-a1ce-2d20d784826a.gif)
e.

**Comment by time4dev** [comment]
I think every update in vite resets the overlay.

**Comment by yuanlin1995** [comment]
yeah;  you are right;
hh thanks a lot;
when the vite trigger the message of update | error； it will reset the overlay;
here is the some reason cause the message of update don't work, and i resolve it;
